$$
  In this erroneous grace program two pairs of a function and a variable have
  the same name each.

  The variable 'name' is declared inside the main function 'name', as well as
  the variable and the function with the name 'a'. The error triggered should
  only happen for the 'a' name.
$$

fun name() : nothing
  var name : char[64];
  var a : int;

  fun a(ref n : int; amount : int) : nothing {
    $ Will add 'amount' to 'n'
    n <- n + amount;
  }

{ $name
  strcpy(name, "I am a message stored in the variable \'name\'.");
  writeString(name);
  writeChar('\n');

  $ Initialization of variable 'a'
  a <- 0;

  $ Function 'a' is called with arguments the variable 'a' and 17.
  a(a, 17);
}
